version: "3"

services:
  about:
    build:
      dockerfile: gpu.Dockerfile
    image: about-gpu-runtime:latest
    container_name: about
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ps | grep -v grep | grep python"]
      interval: 45s
      timeout: 3s
      retries: 3
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    entrypoint: ["python3"]
    command: ["main.py"]
    runtime: nvidia
